apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - wireguard
  - gateways
  - databases
  # - ingress-nginx
  # - intel-device-plugins
  - reflector
  - authentik
