apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources
  - wireguard
  - gateways
  #- wg-easy
  - databases
  - ingress-nginx
  # - netdata
  # - intel-device-plugins
  - reflector
  - authentik
